=== git-marco00/Runtastic_project/Runtastic/myfiles/validatoreConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ParametriConfigurazione">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="parametriDB">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ip" type="xs:string"/>
						    <xs:element name="porta" type="xs:string"/>
						    <xs:element name="nomeDatabase" type="xs:string"/>
						    <xs:element name="userDatabase" type="xs:string"/>
						    <xs:element name="passwordDatabase" type="xs:string"/>
					    </xs:sequence>
				    </xs:complexType>
			    </xs:element>
                
                <xs:element name="xVbox" type="xs:integer"/> 
                <xs:element name="yVbox" type="xs:integer"/>
                
                <xs:element name="nomeSalvataggioCache" type="xs:string"/>
                <xs:element name="coloreBackground" type="xs:string"/>
                
                <xs:element name="indirizzoServer" type="xs:string"/>
			    <xs:element name="portaServer" type="xs:integer"/>	
			    <xs:element name="indirizzoClient" type="xs:string"/>
			    <xs:element name="portaClient" type="xs:integer"/>	
            
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== git-marco00/Runtastic_project/Runtastic/myfiles/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<ParametriConfigurazione xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="validatoreConfig.xsd">
    
    <parametriDB>
        <ip>localhost</ip>
        <porta>3306</porta>
        <nomeDatabase>runtastic</nomeDatabase>
        <userDatabase>root</userDatabase>
        <passwordDatabase></passwordDatabase>
    </parametriDB>

    <xVbox>500</xVbox>
    <yVbox>600</yVbox>
    
    <nomeSalvataggioCache>./myfiles/cache.bin</nomeSalvataggioCache>
    
    <coloreBackground>lightyellow</coloreBackground>

    <indirizzoServer>localhost</indirizzoServer>
	<portaServer>4242</portaServer>
	<indirizzoClient>localhost</indirizzoClient>
	<portaClient>6464</portaClient>

</ParametriConfigurazione>
